from .dummy_model import generate_bias

from .gpt_bias_detection import OAI_get_bias_prediction, OAI_analyze_paragraph

from .custom_bias_detection import CUSTOM_analyze_sentence, CUSTOM_get_bias_prediction